apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: chetbot-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: us-central1-docker.pkg.dev/ta-chetbot/fastapi-full-app/fastapiapp:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: chetbot-kube
spec:
  selector:
    app: fastapi
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-ingress
  namespace: chetbot-kube
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: fastapi-service
      port:
        number: 80